name: Macos

on:
  push:
    paths:
      - "**.cpp"
      - "**.hpp"
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"

jobs:

  build:
    name: Build and test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup Dist/
      env:
        CC: gcc
    - run: cd Dist/ && ninja
    - run: meson test -C Dist/ -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: Dist/meson-logs/testlog.txt
